### PR TITLE
HyREPL did not work with PyPI hy

### PR DESCRIPTION
**Pull request by endrebak**
Added info to documentation

### CODE REVIEW

**Comment by endrebak** [comment]
Let me look into this first; hyrepl might not have worked because I used `python2` to install hy. Let me check. Sorry for the disturbance :)

**Comment by Foxboron** [comment]
No problem, feel free to ping me on IRC `#hy` on Freenode if there is anything \o/

**Comment by endrebak** [comment]
Did not work with `PyPI hy`:

```bash
(py3)bash-3.2$ hy -m HyREPL.server
  File "/Users/endrebakkenstovner/code/HyREPL/HyREPL/server.hy", line 12, column 1

  (defclass ReplServer [ThreadingMixIn TCPServer]
  ^----------------------------------------------
    [allow-reuse-address True])
  ----------------------------^
HyTypeError: Wrong number of argument in defclass attribute.
```

After installing hy develop:

```
(py3)bash-3.2$ hy -m HyREPL.server
Listening on 1337
```

Thanks, never used `IRC`, should probably get on there to ask if someone has a working `emacs-completion` for hy.

**Comment by Foxboron** [comment]
Yes, we are aware. We are going to try a setup where we tag releases along with Hy. But no releases have been done yet, so everything is done according to `master` on hy

**Comment by Foxboron** [comment]
I added the `master.zip` from github as a dependency link in `setup.py` now, so it should work as expected. I'll push too pypi during the day!

**Pull request closed without merging**
