### PR TITLE
Fixed syntax errors

### PR DESCRIPTION
**Pull request by peaceamongworlds**
Fixed old list comp syntax and added support for macro doc strings.

### CODE REVIEW

**Comment by allison-casey** [comment]
@peaceamongworlds I don't think foxboron is very active here, so i made a fork i'm going to try and keep more active if you wanna open this pr [there](https://github.com/allison-casey/HyREPL), i'll merge it. I'd really like  a working nrepl implementation myself

**Comment by Foxboron** [comment]
Yo!

You are correct I haven't worked on this for a while. I'd be happy to either move this repository to you or the hylang org so it can have a proper maintainer :) I don't think having a fork is the best way to solve it.

**Comment by allison-casey** [comment]
Fantastic! I'd be willing to take ownership of this for now. If we can get the bugs ironed out I can move it into hylang. Thank you!

**Comment by Foxboron** [comment]
Do you want me to transfer the repository to you or add you as a maintainer to this repository?

**Comment by allison-casey** [comment]
whichever you prefer, i'm happy with either

**Comment by allison-casey** [comment]
Wonderful! Thank you Foxboron!

**Review by allison-casey — APPROVED** [review]

**Comment by Foxboron** [comment]
My pleasure :)!

**Pull request merged**
